languageCode = "en-us"
defaultContentLanguage = "en"
title = 'Test site for mod-slideshow-gallery'
timeout = "180s"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  replacements = 'github.com/d-oit/hinode-mod-slideshow-gallery -> ../..'
  # Build and serve using local mod-template clone declared in the named Hugo workspace:
  workspace = "hinode-mod-slideshow-gallery.work"
  [[module.imports]]
    path = "github.com/d-oit/hinode-mod-slideshow-gallery"
  [[module.imports]]
    path = "github.com/gethinode/hinode"
  [[module.imports]]
    path = "github.com/gethinode/mod-bootstrap"
  [[module.imports]]
    path = "github.com/gethinode/mod-csp"
  [[module.imports]]
    path = "github.com/gethinode/mod-flexsearch/v3"
  [[module.imports]]
    path = "github.com/gethinode/mod-fontawesome/v2"
  [[module.imports]]
    path = "github.com/gethinode/mod-katex"
  [[module.imports]]
    path = "github.com/gethinode/mod-leaflet"
  [[module.imports]]
    path = "github.com/gethinode/mod-lottie"
  [[module.imports]]
    path = "github.com/gethinode/mod-simple-datatables"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v4"

 
