name: Release

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      force:
        description: 'Force release even if tests failed'
        required: false
        default: false
        type: boolean

jobs:
  check-tests:
    name: Check Test Status
    runs-on: ubuntu-latest
    outputs:
      tests-passed: ${{ steps.check.outputs.tests-passed }}
    
    steps:
      - name: Check test workflow status
        id: check
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]] || [[ "${{ inputs.force }}" == "true" ]]; then
            echo "tests-passed=true" >> $GITHUB_OUTPUT
            echo "✅ Tests passed or force release requested"
          else
            echo "tests-passed=false" >> $GITHUB_OUTPUT
            echo "❌ Tests failed. Release blocked."
            exit 1
          fi

  release:
    name: Create Release
    needs: check-tests
    runs-on: ubuntu-latest
    if: needs.check-tests.outputs.tests-passed == 'true'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GIT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Create GitHub release
        if: steps.semantic-release.outputs.nextRelease
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GIT }}
        run: |
          # Create GitHub release using gh CLI
          gh release create ${{ steps.semantic-release.outputs.nextRelease.version }} \
            --title "${{ steps.semantic-release.outputs.nextRelease.version }}" \
            --notes "${{ steps.semantic-release.outputs.nextRelease.notes }}" \
            --generate-notes

      - name: Notify success
        if: success()
        run: echo "🚀 Release completed successfully"
